# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.cache/wt [current_project]
set_property parent.project_path C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/new/KeyGeneration.v
  C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/new/aes_engine.v
  C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/new/mixcolumn.v
  C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/new/roundlast.v
  C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/new/rounds.v
  C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/new/sbox.v
  C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/new/shiftrow.v
  C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/new/subbytes.v
  C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/new/aes_wrapper.v
}
read_ip -quiet C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/ip/clk_wiz/clk_wiz.xci
set_property used_in_implementation false [get_files -all c:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/ip/clk_wiz/clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc]
set_property used_in_implementation false [get_files -all c:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/constrs_1/new/project.xdc
set_property used_in_implementation false [get_files C:/Users/AliAzak/Desktop/aes_engine_wrapper/aes_engine_wrapper.srcs/constrs_1/new/project.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top aes_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef aes_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file aes_wrapper_utilization_synth.rpt -pb aes_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
